name: Update Weekly News

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests feedparser openai python-dotenv

      - name: Fetch news headlines
        run: python src/fetch_news.py

      - name: Summarise news headlines
        env:
          OPENAI_API_KEY: ${{ secrets.SECRET_GEN_AI_KEY }}
        run: python src/summarise_headlines.py

      - name: Commit and push updated news
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add news.json
          git commit -m "Update weekly news feed"
          git push
